export const CATEGORY_NAMES = {
  RIDDLE: 'Riddle Rosehearts',
  ACE: 'Ace Trappola',
  DEUCE: 'Deuce Spade',
  CATER: 'Cater Diamond',
  TREY: 'Trey Clover',
  LEONA: 'Leona Kingscholar',
  JACK: 'Jack Howl',
  RUGGIE: 'Ruggie Bucchi',
  AZUL: 'Azul Ashengrotto',
  JADE: 'Jade Leech',
  FLOYD: 'Floyd Leech',
  KALIM: 'Kalim Al-Asim',
  JAMIL: 'Jamil Viper',
  VIL: 'Vil Schoenheit',
  EPEL: 'Epel Felmier',
  ROOK: 'Rook Hunt',
  IDIA: 'Idia Shroud',
  ORTHO: 'Ortho Shroud',
  MALLEUS: 'Malleus Draconia',
  SEBEK: 'Sebek Zigvolt',
  SILVER: 'Silver',
  LILIA: 'Lilia Vanrouge',
  GRIM: 'Grim',
  CROWLEY: 'Dire Crowley',
  CREWEL: 'Divus Crewel',
  TREIN: 'Mozus Trein',
  VARGAS: 'Ashton Vargas',
  SAM: 'Sam',
  CHENYA: "Chen'nya",
  CHEKA: 'Cheka',
  MIRROR: 'Dark Mirror',
  LUCIUS: 'Lucius',
};
